version: '3.7'
services:
  mongo:
    image: mongo:4.0.6
    ports:
      - 27017:27017
  kafka:
    image: spotify/kafka
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
    ports:
      - 9092:9092
      - 2181:2181