spring:
  cloud:
    stream:
      bindings:
        new-show:
          group: listener
        live-show:
          group: listener
      kafka:
        binder:
          brokers: cp-kafka:29092
        bindings:
          new-show-listener-notification:
            producer:
              configuration:
                enable.idempotence: true
                retries: 5
                max.in.flight.requests.per.connection: 1
                acks: all