apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-kafka
  labels:
    app: cp-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-kafka
  template:
    metadata:
      labels:
        app: cp-kafka
    spec:
      hostname: cp-kafka
      containers:
        - name: cp-kafka
          image: confluentinc/cp-kafka:5.2.1
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: cp-zookeeper:32181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://cp-kafka:29092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: '1'
          ports:
            - containerPort: 29092
