kind: ConfigMap
apiVersion: v1
metadata:
  name: listener-configmap
  labels:
    app: listener
data:
  application.yaml: |-
    spring:
      data:
        mongodb:
          host: mongo
          socket-timeout: 10000