apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-zookeeper
  labels:
    app: cp-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cp-zookeeper
  template:
    metadata:
      labels:
        app: cp-zookeeper
    spec:
      containers:
        - name: cp-zookeeper
          image: confluentinc/cp-zookeeper:5.2.1
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '32181'
          ports:
            - containerPort: 32181